"""Real Java/LearnLib bridge tests. External jar cache required, no fake learner."""
from pathlib import Path
import copy
import pytest
from experiments.ttt import runner as r


def test_learnlib_ttt_learns_and_exports_exact_hypothesis():
    assert hasattr(r, 'run_trial'), 'real LearnLib bridge is not implemented'
    build = r.prepare_java(Path('/tmp/artifacts'))
    f = r.load_fixtures()[0]
    trial = r.run_trial(f, 0, build)
    assert trial['status'] == 'passed'
    assert trial['hypothesis_states'] == trial['minimal_reference_states'] == 4
    assert trial['mq_count'] > 0 and trial['eq_count'] > 0
    assert trial['symbols_executed'] >= trial['mq_count']
    assert trial['reset_count'] == trial['mq_count']
    assert trial['remaining_counterexample'] is None
    assert trial['learner_class'] == 'de.learnlib.algorithm.ttt.mealy.TTTLearnerMealy'
    damaged = copy.deepcopy(trial['hypothesis'])
    damaged['transitions'][damaged['initial']][0][1] ^= 1
    assert r.product_counterexample(r.build_reference(f), damaged) == [0]


def test_completed_run_report_is_bound_to_sources_and_rejects_corruption():
    assert hasattr(r, 'validate_report'), 'report provenance validation is missing'
    report_path = r.ROOT / 'experiments/results/ttt-v0.1/report.json'
    if not report_path.exists():
        pytest.skip('full registered run report is generated by the experiment CLI')
    import json
    report = json.loads(report_path.read_text())
    assert r.validate_report(report)['status'] == 'passed'
    damaged = copy.deepcopy(report)
    damaged['trials'][0]['hypothesis']['transitions'][0][0][1] ^= 1
    with pytest.raises(ValueError, match='hypothesis|counterexample'):
        r.validate_report(damaged)
    damaged = copy.deepcopy(report)
    damaged['manifest']['source_sha256']['src/bcs/simulator.py'] = '0' * 64
    with pytest.raises(ValueError, match='source'):
        r.validate_report(damaged)


@pytest.mark.parametrize('corruption', [
    'learner_class', 'compiled_class', 'ttt_class', 'zero_counters',
    'erased_counterexamples', 'erased_eq_evidence', 'false_summary',
    'false_negatives', 'negative_destinations',
])
def test_report_validation_rejects_falsified_provenance_and_evidence(corruption):
    import json
    report = json.loads((r.ROOT / 'experiments/results/ttt-v0.1/report.json').read_text())
    trial = report['trials'][0]
    if corruption == 'learner_class':
        trial['learner_class'] = 'com.example.LookupTablePretendingToBeTTT'
    elif corruption == 'compiled_class':
        report['manifest']['compiled_class_sha256'] = '0' * 64
    elif corruption == 'ttt_class':
        report['manifest']['learnlib_ttt_class_sha256'] = '0' * 64
    elif corruption == 'zero_counters':
        trial.update(mq_count=0, reset_count=0, symbols_executed=0)
    elif corruption == 'erased_counterexamples':
        trial['counterexamples'] = []
    elif corruption == 'erased_eq_evidence':
        trial['eq_checks'][0].update(counterexample=None, edges_compared=0)
    elif corruption == 'false_summary':
        report['summary'].update(status='failed', completed_trials=0)
    elif corruption == 'false_negatives':
        report['negative_checks'] = dict.fromkeys(report['negative_checks'], None)
    elif corruption == 'negative_destinations':
        h = trial['hypothesis']
        for row in h['transitions']:
            for transition in row:
                if transition[0] == 0:
                    transition[0] = -len(h['transitions'])
        trial['hypothesis_sha256'] = r.object_digest(h)
    with pytest.raises(ValueError):
        r.validate_report(report)
